# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Momentary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Momentary
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.20.1'

  target 'MomentaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Momentary-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Momentary-tvOS

  target 'Momentary-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
